In [1]:
from predict_absenteeism_script_file import *

In [2]:
data_file = os.path.join(os.path.pardir, 'data', 'external', 'Absenteeism_new_data.csv')

In [3]:
df = pd.read_csv(data_file, delimiter=',')

In [4]:
df = df.drop(['ID'], axis=1)

In [5]:
df

,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets
0,27,01/06/2018,179,26,30,237.656,19,3,0,0
1,7,04/06/2018,361,52,28,237.656,27,1,1,4
2,23,06/06/2018,155,12,34,237.656,25,1,2,0
3,25,08/06/2018,179,22,40,237.656,22,2,2,0
4,10,08/06/2018,155,12,34,237.656,25,1,2,0
5,11,11/06/2018,225,26,28,237.656,24,1,1,2
6,7,13/06/2018,118,15,46,275.089,25,1,2,0
7,27,13/06/2018,179,26,30,275.089,19,3,0,0
8,26,15/06/2018,118,10,37,275.089,28,1,0,0
9,10,20/06/2018,118,10,37,275.089,28,1,0,0
10,22,21/06/2018,378,49,36,275.089,21,1,2,4
11,19,21/06/2018,118,13,50,275.089,31,1,1,0
12,19,22/06/2018,233,51,31,275.089,21,2,1,8
13,27,22/06/2018,179,26,30,275.089,19,3,0,0
14,0,25/06/2018,235,29,48,275.089,33,1,1,5
15,0,28/06/2018,268,11,33,275.089,25,2,0,0
16,19,28/06/2018,118,13,50,275.089,31,1,1,0
17,13,28/06/2018,179,26,30,275.089,19,3,0,0
18,28,28/06/2018,291,31,40,275.089,25,1,1,1
19,13,02/07/2018,179,26,30,275.089,19,3,0,0
20,25,02/07/2018,118,10,37,275.089,28,1,0,0
21,22,05/07/2018,233,51,31,275.089,21,2,1,8
22,8,06/07/2018,118,10,37,275.089,28,1,0,0
23,10,11/07/2018,118,10,37,275.089,28,1,0,0
24,22,11/07/2018,233,51,31,275.089,21,2,1,8
25,26,11/07/2018,235,20,43,264.604,38,1,1,0
26,19,13/07/2018,233,51,31,264.604,21,2,1,8
27,6,16/07/2018,228,14,58,264.604,22,1,2,1
28,28,16/07/2018,118,10,37,264.604,28,1,0,0
29,6,17/07/2018,228,14,58,264.604,22,1,2,1
30,22,17/07/2018,189,29,33,264.604,25,1,2,2
31,23,18/07/2018,118,10,37,264.604,28,1,0,0
32,22,18/07/2018,361,52,28,264.604,27,1,1,4
33,22,18/07/2018,225,26,28,264.604,24,1,1,2
34,13,23/07/2018,369,17,31,264.604,25,1,3,0
35,14,24/07/2018,289,36,33,264.604,30,1,2,1
36,11,24/07/2018,235,11,37,264.604,29,3,1,1
37,0,24/07/2018,118,14,40,271.219,34,1,1,8
38,0,25/07/2018,231,35,39,271.219,35,1,2,2
39,0,27/07/2018,179,45,53,271.219,25,1,1,1

In [6]:
# read the saved model and scalar file
dir_ = os.path.join(os.path.pardir, 'src', 'models')
model_file = os.path.join(dir_, 'absenteeism_model_1.pickle')
scalar_file = os.path.join(dir_, 'absenteeism_scalar_1.pickle')

In [7]:
model = AbsenteeismModel(model_file, scalar_file)

In [8]:
model

In [9]:
# pd.read_csv(data_file)

In [10]:
# Load and clean the data
model.load_and_clean_data(data_file)

/Users/hesbon/Desktop/data-science/absenteeism/notebooks/predict_absenteeism_script_file.py:26: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  X_scaled = pd.DataFrame(self.scalar.transform(X[self.columns]), columns=self.columns)

In [11]:
model.predict_probability()

array([0.574658  , 0.57756395, 0.23898558, 0.55905687, 0.65937309,
       0.64887792, 0.80421539, 0.574658  , 0.41419347, 0.81337552,
       0.20093847, 0.8939704 , 0.95010168, 0.574658  , 0.34616559,
       0.34630114, 0.8939704 , 0.89279675, 0.2738382 , 0.90570493,
       0.44917512, 0.72566801, 0.83406936, 0.83406936, 0.72566801,
       0.32998688, 0.95644647, 0.8696741 , 0.44917512, 0.8696741 ,
       0.27844444, 0.44917512, 0.20370166, 0.25692974, 0.39252743,
       0.57888122, 0.89687285, 0.47514738, 0.16888556, 0.39194011])

In [12]:
model.predicted_output_category()

array([1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0])

In [15]:
predicted_outputs = model.predicted_outputs()

In [16]:
predicted_outputs

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Probability,Prediction
0,0,0.0,0,1,6,179,30,19,1,0,0,0.574658,1
1,1,0.0,0,0,6,361,28,27,0,1,4,0.577564,1
2,0,0.0,0,1,6,155,34,25,0,2,0,0.238986,0
3,0,0.0,0,1,6,179,40,22,1,2,0,0.559057,1
4,1,0.0,0,0,6,155,34,25,0,2,0,0.659373,1
5,1,0.0,0,0,6,225,28,24,0,1,2,0.648878,1
6,1,0.0,0,0,6,118,46,25,0,2,0,0.804215,1
7,0,0.0,0,1,6,179,30,19,1,0,0,0.574658,1
8,0,0.0,0,1,6,118,37,28,0,0,0,0.414193,0
9,1,0.0,0,0,6,118,37,28,0,0,0,0.813376,1
10,0,0.0,0,1,6,378,36,21,0,2,4,0.200938,0
11,0,0.0,1,0,6,118,50,31,0,1,0,0.893970,1
12,0,0.0,1,0,6,233,31,21,1,1,8,0.950102,1
13,0,0.0,0,1,6,179,30,19,1,0,0,0.574658,1
14,0,0.0,0,0,6,235,48,33,0,1,5,0.346166,0
15,0,0.0,0,0,6,268,33,25,1,0,0,0.346301,0
16,0,0.0,1,0,6,118,50,31,0,1,0,0.893970,1
17,1,0.0,0,0,6,179,30,19,1,0,0,0.892797,1
18,0,0.0,0,1,6,291,40,25,0,1,1,0.273838,0
19,1,0.0,0,0,7,179,30,19,1,0,0,0.905705,1
20,0,0.0,0,1,7,118,37,28,0,0,0,0.449175,0
21,0,0.0,0,1,7,233,31,21,1,1,8,0.725668,1
22,1,0.0,0,0,7,118,37,28,0,0,0,0.834069,1
23,1,0.0,0,0,7,118,37,28,0,0,0,0.834069,1
24,0,0.0,0,1,7,233,31,21,1,1,8,0.725668,1
25,0,0.0,0,1,7,235,43,38,0,1,0,0.329987,0
26,0,0.0,1,0,7,233,31,21,1,1,8,0.956446,1
27,1,0.0,0,0,7,228,58,22,0,2,1,0.869674,1
28,0,0.0,0,1,7,118,37,28,0,0,0,0.449175,0
29,1,0.0,0,0,7,228,58,22,0,2,1,0.869674,1
30,0,0.0,0,1,7,189,33,25,0,2,2,0.278444,0
31,0,0.0,0,1,7,118,37,28,0,0,0,0.449175,0
32,0,0.0,0,1,7,361,28,27,0,1,4,0.203702,0
33,0,0.0,0,1,7,225,28,24,0,1,2,0.256930,0
34,1,0.0,0,0,7,369,31,25,0,3,0,0.392527,0
35,1,0.0,0,0,7,289,33,30,0,2,1,0.578881,1
36,1,0.0,0,0,7,235,37,29,1,1,1,0.896873,1
37,0,0.0,0,0,7,118,40,34,0,1,8,0.475147,0
38,0,0.0,0,0,7,231,39,35,0,2,2,0.168886,0
39,0,0.0,0,0,7,179,53,25,0,1,1,0.391940,0

In [19]:
predicted_outputs.to_csv(os.path.join(os.path.pardir, 'src', 'features', 'predicted_absenteeism.csv'), index=0)